export const ActionTypes = {
  STORE_DATA: "STORE_DATA",
  STORE_ID: "STORE_ID",
  STORE_ALL_PROG: "STORE_ALL_PROG",
  SEARCH_PROGS: "SEARCH_PROG",
  SEARCH_PROGS_ID: "SEARCH_PROG_ID",
  SEARCH_PROGS_CAUSE: "SEARCH_PROG_CAUSE",
  SET_MONTH: "SET_MONTH",
  MONTH: "MONTH",
  YEAR: "YEAR",
  NAME: "NAME",
  STORE_BIG_DATA: "STORE_BIG_DATA",
  DELETE_ITEM: "DELETE_ITEM",
};
